# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Orchestrator agent for coordinating due diligence analysis."""

import datetime
from typing import Dict, Any

from google.adk.agents import LlmAgent, SequentialAgent
from google.adk.tools import google_search
from pydantic import BaseModel, Field

from ..config import config, prompts
from .callbacks import (
    track_agent_execution_callback,
    update_analysis_progress_callback,
)


class AnalysisPlan(BaseModel):
    """Model for the analysis plan generated by orchestrator."""
    
    startup_overview: str = Field(..., description="Brief overview of the startup")
    key_focus_areas: list[str] = Field(..., description="Key areas to focus analysis on")
    team_analysis_priorities: list[str] = Field(..., description="Team analysis priorities")
    market_analysis_priorities: list[str] = Field(..., description="Market analysis priorities")
    product_analysis_priorities: list[str] = Field(..., description="Product analysis priorities")
    competition_analysis_priorities: list[str] = Field(..., description="Competition analysis priorities")
    special_considerations: list[str] = Field(
        default_factory=list, description="Special considerations or red flags"
    )
    estimated_completion_time: int = Field(..., description="Estimated completion time in minutes")


orchestrator_agent = LlmAgent(
    model=config.orchestrator_model,
    name="orchestrator_agent",
    description="Orchestrates the complete due diligence analysis workflow",
    instruction=f"""
    {prompts.orchestrator_prompt}
    
    You are analyzing a startup submission for investment due diligence. Your task is to:
    
    1. **ANALYZE THE SUBMISSION**: Review all provided startup information including:
       - Company information and business description
       - Founder profiles and team composition
       - Uploaded documents (pitch decks, financial models, etc.)
       - Market positioning and competitive landscape claims
       - Traction metrics and business model
    
    2. **CREATE COMPREHENSIVE ANALYSIS PLAN**: Based on your analysis, create a detailed plan that includes:
       - Startup overview and key value propositions
       - Specific focus areas for each specialist agent
       - Priority questions that need to be answered
       - Special considerations or potential red flags
       - Estimated timeline for completion
    
    3. **DELEGATE TO SPECIALISTS**: Your plan will guide the following specialist agents:
       - **Team Agent**: Focus on founder-market fit, experience, team completeness
       - **Market Agent**: Validate market size (TAM/SAM/SOM), trends, timing
       - **Product Agent**: Assess product-market fit, traction, scalability
       - **Competition Agent**: Map competitive landscape, identify moat
    
    4. **QUALITY ASSURANCE**: Ensure your plan covers all critical investment criteria:
       - Team strength and execution capability
       - Market opportunity and timing
       - Product differentiation and traction
       - Competitive positioning and defensibility
       - Financial viability and scalability
       - Risk factors and mitigation strategies
    
    **OUTPUT REQUIREMENTS**:
    - Provide a structured analysis plan using the AnalysisPlan model
    - Be specific about what each agent should investigate
    - Highlight any areas requiring special attention
    - Include timeline estimates for realistic expectations
    
    **SEARCH USAGE**:
    Only use google_search if you need to clarify ambiguous company names, verify basic facts, 
    or understand industry context. Do NOT conduct detailed research - that's for the specialist agents.
    
    Current date: {datetime.datetime.now().strftime("%Y-%m-%d")}
    """,
    tools=[google_search],
    output_schema=AnalysisPlan,  # Changed to output_schema as per ADK docs
    output_key="analysis_plan",
    after_agent_callback=track_agent_execution_callback,
)
